"""Tls key length

Revision ID: a7e53883cf4f
Revises: 32ecfb6a24a9
Create Date: 2025-07-22 12:58:19.471173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e53883cf4f'
down_revision: Union[str, Sequence[str], None] = '32ecfb6a24a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tls', 'key',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tls', 'key',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###
