"""create except_ips

Revision ID: d73b2ada2379
Revises: a88cd32b7f08
Create Date: 2025-09-13 23:34:43.169046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73b2ada2379'
down_revision: Union[str, Sequence[str], None] = 'a88cd32b7f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excepted_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excepted_ip')
    # ### end Alembic commands ###
